# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example hello function
#' 
#' @details Creates a pointless two element mekiiiiiiii anjeeeeeeeenngggggg
#'
#' @export
#' @examples
#' rcpp_hello_world()
rcpp_hello_world <- function() {
    .Call('_dbscanDATA501_rcpp_hello_world', PACKAGE = 'dbscanDATA501')
}

