# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_neighbours <- function(dist_vec, eps) {
    .Call('_dbscanDATA501_find_neighbours', PACKAGE = 'dbscanDATA501', dist_vec, eps)
}

create_init_clusters <- function(dist_mat, eps, min_pts, neigh_pts, labs, clust_num) {
    .Call('_dbscanDATA501_create_init_clusters', PACKAGE = 'dbscanDATA501', dist_mat, eps, min_pts, neigh_pts, labs, clust_num)
}

expand_clusters <- function(dist_mat, eps, core_pts, noncore_pts, labs) {
    .Call('_dbscanDATA501_expand_clusters', PACKAGE = 'dbscanDATA501', dist_mat, eps, core_pts, noncore_pts, labs)
}

